#!/bin/bash

MUSIC="/mnt/ehdd2/Music/"
case "$1" in
    files) tree -a $MUSIC | tail -n1 | awk -F\  '{print $3}';;
    size) echo "$(du -hs $MUSIC | cut -c 1-4)B";;
    amount) w3m -dump https://libre.fm/user/phate6660/stats | grep Total | sed "s/[^0-9]//g";;
esac
